### ISSUE TITLE
Incomplete usage (requirements) description

### ISSUE THREAD

**Issue by adasium** [tsoding/xkcd-indexer#3]
The project requires base-4.12 package which is provided for ghc-8.6.x according to https://wiki.haskell.org/Base_package.
It would be useful to provide required ghc version in the README.md or the link above to help the user figure out target ghc version.

**Comment by rexim** [comment]
@milochadam I mentioned the expected version of GHC in README. Plus I configured stack build which automatically downloads the required version of GHC for you.

Please check it out and close the issue if your concern was addressed appropriately.

**Comment by adasium** [comment]
Looks good to me! :+1:
Thank you for your contribution!
